package collector

var (
	statsMetricInfo = map[string]MetricInfo{
		"cluster_size": MetricInfo{
			MetricType: Float,
			Name:       "cluster_size",
			Help:       "Size of Aerospike cluster",
			Labels:     []string{"addr", "alias"},
		},
		"cluster_key": MetricInfo{
			MetricType: String,
			Name:       "cluster_key",
			Help:       "Key of Aerospike cluster",
			Labels:     []string{"addr", "alias", "key"},
		},
		"cluster_integrity": MetricInfo{
			MetricType: Bool,
			Name:       "cluster_integrity",
			Help:       "Is Integrity of Aerospike cluster maintained ?",
			Labels:     []string{"addr", "alias"},
		},
		"cluster_is_member": MetricInfo{
			MetricType: Bool,
			Name:       "cluster_is_member",
			Help:       "Is node member of Aerospike cluster",
			Labels:     []string{"addr", "alias"},
		},
		"uptime": MetricInfo{
			MetricType: Float,
			Name:       "uptime",
			Help:       "Uptime of Aerospike node",
			Labels:     []string{"addr", "alias"},
		},
		"system_free_mem_pct": MetricInfo{
			MetricType: Float,
			Name:       "system_free_mem_pct",
			Help:       "Percent of free memory on system",
			Labels:     []string{"addr", "alias"},
		},
		"system_swapping": MetricInfo{
			MetricType: Bool,
			Name:       "system_swapping",
			Help:       "Is swapping allowed on system?",
			Labels:     []string{"addr", "alias"},
		},
		"heap_allocated_kbytes": MetricInfo{
			MetricType: Float,
			Name:       "heap_allocated_kbytes",
			Help:       "Kilobytes of memory allocated to heap",
			Labels:     []string{"addr", "alias"},
		},
		"heap_active_kbytes": MetricInfo{
			MetricType: Float,
			Name:       "heap_active_kbytes",
			Help:       "Kilobytes of memory active in heap",
			Labels:     []string{"addr", "alias"},
		},
		"heap_mapped_kbytes": MetricInfo{
			MetricType: Float,
			Name:       "heap_mapped_kbytes",
			Help:       "Kilobytes of memeory mapped to heap",
			Labels:     []string{"addr", "alias"},
		},
		"heap_efficiency_pct": MetricInfo{
			MetricType: Float,
			Name:       "heap_efficiency_pct",
			Help:       "Percent of Heap efficiency",
			Labels:     []string{"addr", "alias"},
		},
		"heap_site_count": MetricInfo{
			MetricType: Float,
			Name:       "heap_site_count",
			Help:       "Number of heap sites",
			Labels:     []string{"addr", "alias"},
		},
		"objects": MetricInfo{
			MetricType: Float,
			Name:       "objects",
			Help:       "Number of objects in Aerospike node",
			Labels:     []string{"addr", "alias"},
		},
		"tombstones": MetricInfo{
			MetricType: Float,
			Name:       "tombstones",
			Help:       "Number of tombstones in Aerospike node",
			Labels:     []string{"addr", "alias"},
		},
		"tsvc_queue": MetricInfo{
			MetricType: Float,
			Name:       "tsvc_queue",
			Help:       "Size of tsvc queue",
			Labels:     []string{"addr", "alias"},
		},
		"info_queue": MetricInfo{
			MetricType: Float,
			Name:       "info_queue",
			Help:       "Size of info queue",
			Labels:     []string{"addr", "alias"},
		},
		"delete_queue": MetricInfo{
			MetricType: Float,
			Name:       "delete_queue",
			Help:       "Size of delete queue",
			Labels:     []string{"addr", "alias"},
		},
		"rw_in_progress": MetricInfo{
			MetricType: Float,
			Name:       "rw_in_progress",
			Help:       "Number of rw in progress",
			Labels:     []string{"addr", "alias"},
		},
		"proxy_in_progress": MetricInfo{
			MetricType: Float,
			Name:       "proxy_in_progress",
			Help:       "Number of proxy in progress",
			Labels:     []string{"addr", "alias"},
		},
		"tree_gc_queue": MetricInfo{
			MetricType: Float,
			Name:       "tree_gc_queue",
			Help:       "Size of tree_gc queue",
			Labels:     []string{"addr", "alias"},
		},
		"client_connections": MetricInfo{
			MetricType: Float,
			Name:       "cient_connections",
			Help:       "Nunber of client connections",
			Labels:     []string{"addr", "alias"},
		},
		"heartbeat_connections": MetricInfo{
			MetricType: Float,
			Name:       "heartbeat_connections",
			Help:       "Number of heartbeat connections",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_connections": MetricInfo{
			MetricType: Float,
			Name:       "fabric_connections",
			Help:       "Nunber of fabric connections",
			Labels:     []string{"addr", "alias"},
		},
		"heartbeat_received_self": MetricInfo{
			MetricType: Float,
			Name:       "heartbeat_received_self",
			Help:       "Number of heartbeat received from itself",
			Labels:     []string{"addr", "alias"},
		},
		"heartbeat_received_foreign": MetricInfo{
			MetricType: Float,
			Name:       "heartbeat_received_foreign",
			Help:       "Number of heartbeat received from foreign",
			Labels:     []string{"addr", "alias"},
		},
		"reaped_fds": MetricInfo{
			MetricType: Float,
			Name:       "reaped_fds",
			Help:       "Number of reaped fds",
			Labels:     []string{"addr", "alias"},
		},
		"info_complete": MetricInfo{
			MetricType: Float,
			Name:       "info_complete",
			Help:       "Number of completed info",
			Labels:     []string{"addr", "alias"},
		},
		"proxy_retry": MetricInfo{
			MetricType: Float,
			Name:       "proxy_retry",
			Help:       "Number of retried proxy",
			Labels:     []string{"addr", "alias"},
		},
		"demarshal_error": MetricInfo{
			MetricType: Float,
			Name:       "demarshal_error",
			Help:       "Number of demarshal error",
			Labels:     []string{"addr", "alias"},
		},
		"early_tsvc_client_error": MetricInfo{
			MetricType: Float,
			Name:       "early_tsvc_client_error",
			Help:       "Number of early_tsvc_client error",
			Labels:     []string{"addr", "alias"},
		},
		"early_tsvc_batch_sub_error": MetricInfo{
			MetricType: Float,
			Name:       "early_tsvc_batch_sub_error",
			Help:       "Number of early_tsvc_batch_sub error",
			Labels:     []string{"addr", "alias"},
		},
		"early_tsvc_udf_sub_error": MetricInfo{
			MetricType: Float,
			Name:       "early_tsvc_udf_sub_error",
			Help:       "Number of early_tsvc_udf_sub error",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_initiate": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_initiate",
			Help:       "Count of batch_index_initiate",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_complete": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_complete",
			Help:       "NUmber of completed batch_index",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_error": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_error",
			Help:       "NUmber of batch_index error",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_timeout": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_timeout",
			Help:       "Timeout of batch_index",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_unused_buffers": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_unused_buffers",
			Help:       "NUmber of batch_index unused buffers",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_huge_buffers": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_huge_buffers",
			Help:       "NUmber of batch_index huge buffers",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_created_buffers": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_created_buffers",
			Help:       "NUmber of batch_index created buffers",
			Labels:     []string{"addr", "alias"},
		},
		"batch_index_destroyed_buffers": MetricInfo{
			MetricType: Float,
			Name:       "batch_index_destroyed_buffers",
			Help:       "NUmber of batch_index destroyed buffers",
			Labels:     []string{"addr", "alias"},
		},
		"batch_initiate": MetricInfo{
			MetricType: Float,
			Name:       "batch_initiate",
			Help:       "batch initiate",
			Labels:     []string{"addr", "alias"},
		},
		"batch_queue": MetricInfo{
			MetricType: Float,
			Name:       "batch_queue",
			Help:       "Size of batch queue",
			Labels:     []string{"addr", "alias"},
		},
		"batch_error": MetricInfo{
			MetricType: Float,
			Name:       "batch_error",
			Help:       "Number of batch error",
			Labels:     []string{"addr", "alias"},
		},
		"batch_timeout": MetricInfo{
			MetricType: Float,
			Name:       "batch_timeout",
			Help:       "Timeout of batch",
			Labels:     []string{"addr", "alias"},
		},
		"scans_active": MetricInfo{
			MetricType: Float,
			Name:       "scans_active",
			Help:       "Number of active scans",
			Labels:     []string{"addr", "alias"},
		},
		"query_short_running": MetricInfo{
			MetricType: Float,
			Name:       "query_short_running",
			Help:       "Number of running short query",
			Labels:     []string{"addr", "alias"},
		},
		"query_long_running": MetricInfo{
			MetricType: Float,
			Name:       "query_long_running",
			Help:       "Number of running long query",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_ucgarbage_found": MetricInfo{
			MetricType: Float,
			Name:       "sindex_ucgarbage_found",
			Help:       "Number of sindex_ucgarbage found",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_locktimedout": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_locktimedout",
			Help:       "Locktimedout of sindex_gc",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_list_creation_time": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_list_creation_time",
			Help:       "Creation time of sindex_gc list",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_list_deletion_time": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_list_deletion_time",
			Help:       "Deletion time of  sindex_gc list",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_objects_validated": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_objects_validated",
			Help:       "Number of validated sindex_gc objects",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_garbage_found": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_garbage_found",
			Help:       "Number of sindex_gc_garbage found",
			Labels:     []string{"addr", "alias"},
		},
		"sindex_gc_garbage_cleaned": MetricInfo{
			MetricType: Float,
			Name:       "sindex_gc_garbage_cleaned",
			Help:       "Number of sindex_gc_garbage cleaned",
			Labels:     []string{"addr", "alias"},
		},
		"paxos_principal": MetricInfo{
			MetricType: String,
			Name:       "paxos_principal",
			Help:       "Aerospike paxos principal",
			Labels:     []string{"addr", "alias", "paxos_principal"},
		},
		"migrate_allowed": MetricInfo{
			MetricType: Bool,
			Name:       "migrate_allowed",
			Help:       "Is migrate allowed ?",
			Labels:     []string{"addr", "alias"},
		},
		"migrate_partitions_remaining": MetricInfo{
			MetricType: Float,
			Name:       "migrate_partitions_remaining",
			Help:       "Number of migrate_partitions remaining",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_bulk_send_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_bulk_send_rate",
			Help:       "Rate of sent fabric_bulk",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_bulk_recv_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_bulk_recv_rate",
			Help:       "Rate of received fabric_bulk",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_ctrl_send_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_ctrl_send_rate",
			Help:       "Rate of sent fabric_ctrl",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_ctrl_recv_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_ctrl_recv_rate",
			Help:       "Rate of received fabric_ctrl",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_meta_send_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_meta_send_rate",
			Help:       "Rate of sent fabric_meta",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_meta_recv_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_meta_recv_rate",
			Help:       "Rate of received fabric_meta",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_rw_send_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_rw_send_rate",
			Help:       "Rate of sent fabric_rw",
			Labels:     []string{"addr", "alias"},
		},
		"fabric_rw_recv_rate": MetricInfo{
			MetricType: Float,
			Name:       "fabric_rw_recv_rate",
			Help:       "Rate of receivied fabric_rw",
			Labels:     []string{"addr", "alias"},
		},
	}
)
