package metrics

var (
	// statsInfo stores aerospike stats field to metric meta mapping
	statsInfo = map[string]Info{
		"cluster_size": Info{
			Type:      Float,
			Name:      "cluster_size",
			Help:      "Size of Aerospike cluster",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"cluster_key": Info{
			Type:      String,
			Name:      "cluster_key",
			Help:      "Key of Aerospike cluster",
			Labels:    []string{"addr", "alias", "key"},
			Subsystem: "stats",
		},
		"cluster_integrity": Info{
			Type:      Bool,
			Name:      "cluster_integrity",
			Help:      "Is Integrity of Aerospike cluster maintained ?",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"cluster_is_member": Info{
			Type:      Bool,
			Name:      "cluster_is_member",
			Help:      "Is node member of Aerospike cluster",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"uptime": Info{
			Type:      Float,
			Name:      "uptime",
			Help:      "Uptime of Aerospike node",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"system_free_mem_pct": Info{
			Type:      Float,
			Name:      "system_free_mem_pct",
			Help:      "Percent of free memory on system",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"system_swapping": Info{
			Type:      Bool,
			Name:      "system_swapping",
			Help:      "Is swapping allowed on system?",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heap_allocated_kbytes": Info{
			Type:      Float,
			Name:      "heap_allocated_kbytes",
			Help:      "Kilobytes of memory allocated to heap",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heap_active_kbytes": Info{
			Type:      Float,
			Name:      "heap_active_kbytes",
			Help:      "Kilobytes of memory active in heap",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heap_mapped_kbytes": Info{
			Type:      Float,
			Name:      "heap_mapped_kbytes",
			Help:      "Kilobytes of memeory mapped to heap",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heap_efficiency_pct": Info{
			Type:      Float,
			Name:      "heap_efficiency_pct",
			Help:      "Percent of Heap efficiency",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heap_site_count": Info{
			Type:      Float,
			Name:      "heap_site_count",
			Help:      "Number of heap sites",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"objects": Info{
			Type:      Float,
			Name:      "objects",
			Help:      "Number of objects in Aerospike node",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"tombstones": Info{
			Type:      Float,
			Name:      "tombstones",
			Help:      "Number of tombstones in Aerospike node",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"tsvc_queue": Info{
			Type:      Float,
			Name:      "tsvc_queue",
			Help:      "Size of tsvc queue",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"info_queue": Info{
			Type:      Float,
			Name:      "info_queue",
			Help:      "Size of info queue",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"delete_queue": Info{
			Type:      Float,
			Name:      "delete_queue",
			Help:      "Size of delete queue",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"rw_in_progress": Info{
			Type:      Float,
			Name:      "rw_in_progress",
			Help:      "Number of rw in progress",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"proxy_in_progress": Info{
			Type:      Float,
			Name:      "proxy_in_progress",
			Help:      "Number of proxy in progress",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"tree_gc_queue": Info{
			Type:      Float,
			Name:      "tree_gc_queue",
			Help:      "Size of tree_gc queue",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"client_connections": Info{
			Type:      Float,
			Name:      "cient_connections",
			Help:      "Nunber of client connections",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heartbeat_connections": Info{
			Type:      Float,
			Name:      "heartbeat_connections",
			Help:      "Number of heartbeat connections",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_connections": Info{
			Type:      Float,
			Name:      "fabric_connections",
			Help:      "Nunber of fabric connections",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heartbeat_received_self": Info{
			Type:      Float,
			Name:      "heartbeat_received_self",
			Help:      "Number of heartbeat received from itself",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"heartbeat_received_foreign": Info{
			Type:      Float,
			Name:      "heartbeat_received_foreign",
			Help:      "Number of heartbeat received from foreign",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"reaped_fds": Info{
			Type:      Float,
			Name:      "reaped_fds",
			Help:      "Number of reaped fds",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"info_complete": Info{
			Type:      Float,
			Name:      "info_complete",
			Help:      "Number of completed info",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"proxy_retry": Info{
			Type:      Float,
			Name:      "proxy_retry",
			Help:      "Number of retried proxy",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"demarshal_error": Info{
			Type:      Float,
			Name:      "demarshal_error",
			Help:      "Number of demarshal error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"early_tsvc_client_error": Info{
			Type:      Float,
			Name:      "early_tsvc_client_error",
			Help:      "Number of early_tsvc_client error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"early_tsvc_batch_sub_error": Info{
			Type:      Float,
			Name:      "early_tsvc_batch_sub_error",
			Help:      "Number of early_tsvc_batch_sub error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"early_tsvc_udf_sub_error": Info{
			Type:      Float,
			Name:      "early_tsvc_udf_sub_error",
			Help:      "Number of early_tsvc_udf_sub error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_initiate": Info{
			Type:      Float,
			Name:      "batch_index_initiate",
			Help:      "Count of batch_index_initiate",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_complete": Info{
			Type:      Float,
			Name:      "batch_index_complete",
			Help:      "NUmber of completed batch_index",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_error": Info{
			Type:      Float,
			Name:      "batch_index_error",
			Help:      "NUmber of batch_index error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_timeout": Info{
			Type:      Float,
			Name:      "batch_index_timeout",
			Help:      "Timeout of batch_index",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_unused_buffers": Info{
			Type:      Float,
			Name:      "batch_index_unused_buffers",
			Help:      "NUmber of batch_index unused buffers",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_huge_buffers": Info{
			Type:      Float,
			Name:      "batch_index_huge_buffers",
			Help:      "NUmber of batch_index huge buffers",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_created_buffers": Info{
			Type:      Float,
			Name:      "batch_index_created_buffers",
			Help:      "NUmber of batch_index created buffers",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_index_destroyed_buffers": Info{
			Type:      Float,
			Name:      "batch_index_destroyed_buffers",
			Help:      "NUmber of batch_index destroyed buffers",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_initiate": Info{
			Type:      Float,
			Name:      "batch_initiate",
			Help:      "batch initiate",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_queue": Info{
			Type:      Float,
			Name:      "batch_queue",
			Help:      "Size of batch queue",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_error": Info{
			Type:      Float,
			Name:      "batch_error",
			Help:      "Number of batch error",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"batch_timeout": Info{
			Type:      Float,
			Name:      "batch_timeout",
			Help:      "Timeout of batch",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"scans_active": Info{
			Type:      Float,
			Name:      "scans_active",
			Help:      "Number of active scans",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"query_short_running": Info{
			Type:      Float,
			Name:      "query_short_running",
			Help:      "Number of running short query",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"query_long_running": Info{
			Type:      Float,
			Name:      "query_long_running",
			Help:      "Number of running long query",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_ucgarbage_found": Info{
			Type:      Float,
			Name:      "sindex_ucgarbage_found",
			Help:      "Number of sindex_ucgarbage found",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_locktimedout": Info{
			Type:      Float,
			Name:      "sindex_gc_locktimedout",
			Help:      "Locktimedout of sindex_gc",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_list_creation_time": Info{
			Type:      Float,
			Name:      "sindex_gc_list_creation_time",
			Help:      "Creation time of sindex_gc list",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_list_deletion_time": Info{
			Type:      Float,
			Name:      "sindex_gc_list_deletion_time",
			Help:      "Deletion time of  sindex_gc list",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_objects_validated": Info{
			Type:      Float,
			Name:      "sindex_gc_objects_validated",
			Help:      "Number of validated sindex_gc objects",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_garbage_found": Info{
			Type:      Float,
			Name:      "sindex_gc_garbage_found",
			Help:      "Number of sindex_gc_garbage found",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"sindex_gc_garbage_cleaned": Info{
			Type:      Float,
			Name:      "sindex_gc_garbage_cleaned",
			Help:      "Number of sindex_gc_garbage cleaned",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"paxos_principal": Info{
			Type:      String,
			Name:      "paxos_principal",
			Help:      "Aerospike paxos principal",
			Labels:    []string{"addr", "alias", "paxos_principal"},
			Subsystem: "stats",
		},
		"migrate_allowed": Info{
			Type:      Bool,
			Name:      "migrate_allowed",
			Help:      "Is migrate allowed ?",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"migrate_partitions_remaining": Info{
			Type:      Float,
			Name:      "migrate_partitions_remaining",
			Help:      "Number of migrate_partitions remaining",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_bulk_send_rate": Info{
			Type:      Float,
			Name:      "fabric_bulk_send_rate",
			Help:      "Rate of sent fabric_bulk",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_bulk_recv_rate": Info{
			Type:      Float,
			Name:      "fabric_bulk_recv_rate",
			Help:      "Rate of received fabric_bulk",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_ctrl_send_rate": Info{
			Type:      Float,
			Name:      "fabric_ctrl_send_rate",
			Help:      "Rate of sent fabric_ctrl",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_ctrl_recv_rate": Info{
			Type:      Float,
			Name:      "fabric_ctrl_recv_rate",
			Help:      "Rate of received fabric_ctrl",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_meta_send_rate": Info{
			Type:      Float,
			Name:      "fabric_meta_send_rate",
			Help:      "Rate of sent fabric_meta",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_meta_recv_rate": Info{
			Type:      Float,
			Name:      "fabric_meta_recv_rate",
			Help:      "Rate of received fabric_meta",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_rw_send_rate": Info{
			Type:      Float,
			Name:      "fabric_rw_send_rate",
			Help:      "Rate of sent fabric_rw",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
		"fabric_rw_recv_rate": Info{
			Type:      Float,
			Name:      "fabric_rw_recv_rate",
			Help:      "Rate of receivied fabric_rw",
			Labels:    []string{"addr", "alias"},
			Subsystem: "stats",
		},
	}
)
